[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "f0ceef6c683b6b7af5fd02481accb32f8bac0486"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "82db119952b02dfa8c81aa73c64ca2f870be8ae0ce5aadc64ce820cf409df1f9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "c43d1b14ea89949dc0fbeb710b3daebe7e1f6fc0"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e459e3713b3870dbcbca45f0662e76058e7ed2267383df3e7f4b2a8233e814ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "1279320997439476831fdb6a9fa0cf3d50ab2449"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "de798bba48af659e70931ce3c9998c09e0c8204faef7cf5c14b2c7d6ed945d0c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "be5570308a756679425ca6a59836767ad4a3a8a3"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "f0d3b0917b591244c665be7ae6d40e51483d22f120e49a186569c2f3bfb8bdd2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "568d0e6dcb9ec6e10cefc3f9c2b9d148adadb60c"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a596e9fd8af0abc74551ff6e14a84ddee09d89bbe27f56d551e858ba4d729ae7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a418465b949d48abb29cd7e3b232124c6fe21e3e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "38ae79c301a9bce4e9709df06accc5af445fd7bdf58d01a40b0d9de00d3f9c38"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13da41cb1caa00de91afac7c7727994e400aedc6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "520decf8d95773cb114990d629207a4e90a0e8343b672510eaf952f2a41b6a6a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b91a6bfd63485ba689a109ec4b3c21be0b7c2b9c"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "820e165ebe509f15848f02c9b6bdbd94bc091cd0bb5e092a6edb245aada2a4ba"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "13eaa38fad83e0d114b6a75626ddcf60825c9a35"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3b7c621e54342e49476310513471f7321fb5e9071c993b0193900d909993e439"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "8116734abaa2c190e7d9bc67f8ad02c0f883ba7d"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3414b384cb69d71d95ebf91071989ddeb07f59c109f2f9eaeb8b4580705d72ec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "9637e672af38fb7f89540f01d199d3930a898c6f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "75ef1038e212e437739e4acb594e2cabf2d3c50df94935819d61ddaefa62168c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "c97a8880435aa6ce2457634a430eec65d1c332d6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e022ccc1ebaa82a5b875a9dd3ebb927506cc8d5da67eaf20f15020685af67204"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "442cfd5b8c0d9e10bd44be4da87c679f1eab0c5a"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "d99984d99f4e5707051babdc4cc914710c56cdd77640b1f5b6938702a5e40041"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "5ad379a6846bb80c8e8a3f38fdde1d5f74065423"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "5672b30f3001fa5d165906bae0d93310e5aeac807668ec4fffd5f00e76467976"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "d4dbc10dce10146e1fc50ee330c63e08f5d0150e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "03f82af718c6a79637a4bbf5a0144782ceea98e557e62a57c04a421968ce4a8b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "944142396341a55bdeec61978320842846468a7c"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "7ece8b32aedb9dd344f173b7fe15f0d7afc7a413ed0a44f1068d2e3d8571f66e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "f91e217c8008d4d0a73d5d6f460e778246f9ec6b"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "4f3b938beeaf0005fc09b668f41231df0ab849ab2a9b036a842e24838388080e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.2+0/aws_c_common.v0.11.2.x86_64-w64-mingw32.tar.gz"
