[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "2a7091a338bc2682377bfc100caecbd8ad90c14f"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "dfe4d4437fc4e9e66f9080d5bc62bdab85c9c72527f86b4179577743cc3d8a1c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "f7ac9730a50f714e16652b01e0fafcdd131e7550"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "901c7f3c55b506d43d643c95d05985090e27a9db004ff4ce252e1a079365068a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "58f0562a6f384023ab78d11adb88c24e977c32c2"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c862d98572277ef22772f7ecd5e8c232621d2f1726b9f737abd1cb08281fd908"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd09d14de64f7fa79434017355e77c63fec56d92"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9b31f5da5a91568b045021cd169edee060bf90d161b48b84c801aab8a683c959"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2783b13b80871ae3e85d930b1fe922672368c49e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9d181c2bccf34e56178a9fc34ce0b77d656e5d3db4dd195116d0d12ccd99e8a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bff3a1c81f05f6ddd56b1e6aaf3f1bfe1149623"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "77815d140ef6697af2c3b30c41bc548ea977b27102a021c37c53b822e8b3945d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c68350cefd4463b0db603caf94fdb6699c17579f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e3d3df4451e4ed06cf569d4aa5773cbfa0601650042a0236b0b322ca028e7094"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "951543bf0c17987b59f78b3fffb140e4f5116d6b"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ee3c22a1a3b316a89faf60d4cdab958c70d41c2757496cd894b47728318df052"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "54b57c43e72873dd806687010ac3febac736b29e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "aa90327ddca2d83ffd37b89e0dcd7d0acb395f6970dabd82d3ac436704cdf272"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "b62f8bfb153f61f615c120bb8741c32d6a416582"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c12b2b3fb5444b97be72912b1ae47805be30ca296afbeddd3d41e3a421304218"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "ef92770e20bfa93d7fe461c4f164314d1a48cf6b"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "a84aa9b2580448d223566068df3c0e4136aef5681d089bdc836403f7851f1d07"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c983a4f3ce7ca214cdd6a543d20b7292e9e603c9"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2984dbba9c37c75f449e709ddfc31f21217bec02e1718c8077ae5b06adc9f4e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "61e306263a5c18c82354e35e8945c3e07d52c442"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "abab7a5da4425490c558412aba9eb61389ba893e37749a9fbc3ac260a779dbfc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "660bd5e0b3c94a343425aab78f1c8ffcf48cd7b8"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "fb33b0f5e9f58dc3453ac97edf3079e1aefee7257cc48489de7eaa77619a93c4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "da3765841ddc70639bbe2d4c2884a0c19534e5a8"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "300ab13fe6362f20bda489add81395966be3f41eae11f379d989df10b05d8aa1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.14+0/aws_c_common.v0.9.14.x86_64-w64-mingw32.tar.gz"
