[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "1a010ff8b8278069f288fbf362d6550c9c6f09ad"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "ecc847cf47bda8bae71a4bc4b68a2f4ccc6a267da90f6bd89041ab853eccf09e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "01b2d93e5c4155c6afe84946168da2ac5166a6ae"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4850098f50c196eb72d02e5228e88a73066c4f037f35b64a618db4d4f977e13e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "067ce97ac7e8c1aa098d8b6f7f6075e730c6f5ab"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d1aa6b56c45801ab65e242cc178c1e82477af2edab71bd46db9858aef7054f4b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "ece0e128b2383f880498d51e36bf514de2a2af92"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "0371147d67dc132f1bd60382ab94084ab14f2f8a93c69ed331829cfab51b8129"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe749bc1702bb77d6bc2abf9ffebad1b5863cfa4"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "bc3a08da956eca90176c75c4f22b09c50529076409c9534206be3116811530e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff5183d0ea0387c757fb428ea679ae6671c92475"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "18892dfd5071f117b6c8e97121faa1cf67425f754b3783d2beba39a43a7b5195"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "020d2c4fb5105f30cefec4129b0bd4c49a9e6f45"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9d892b5875a7d658b85a83723aad9651e76aac1a5ce6b26f0915ace8c3289112"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2668429b906ded4385b08f8a7fb9a0c13b05ebcc"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "056469c534d0fdc3654297962a6503b2bd686861d0c4eeaf0aca462f3d11e108"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "9e8351d266339d7323545b4f0e37b461021013a2"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3a8393f923572d568b72b564d4f9c6dd93aa5e6a41bb448303dbc68317ac9272"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "28fcbbecc8d063c78d39ef555253c3b98b8c62e1"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8eca15d5824eb6bd8d005bf1029b1fd2f674c170610f74230dfe9d83f2a16cf5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "3ecabe2ecdc49586ab68adb3d35cc3ca351a8825"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "418bc084f9d31a0edacda6d77e9ce142ae5a4594874ac290e4090c69985fb974"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "8385f160df04cfde34a373d563cf3cc61673aead"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "40ac3f2fae7e9ec1714760aba9b3d7eda3c5a046112df438a7fde3703b49ecfe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "81c525c57870bc80591eed7434615005a1544642"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "a4faf14dad87c8b9aca8ead8a40e76dd47b737c76750cd024b3a80561b3d93f5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "6e03248bd890e4921948f598caf75c76621024aa"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "55c284f135e4b6317159cf8dd2613503bdace6fb95966ed578f158a2811a00cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c28be5d35eed3f28c0bc09e61c01f53ee059f128"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "91acfc6983a6450371164baf35c601760dd8536379a6df5b3174aac2813d1e0e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "81bc81e5cf25ff57cad1380978b60324ffff98b1"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "2db0a9d9407a6a447d47bbd4dfce04b59e22b082ff9d64459f134239785b4e83"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "b6ff8417c439f8083f62fa0e9278144b169a6520"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "4c07da8475a4d6dd5da05fc72c997ae91a858d36d9e1d5ea0271e61ac3952f25"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.4+0/aws_c_common.v0.12.4.x86_64-w64-mingw32.tar.gz"
