[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "ef3ffc8aabbf5c7350a6de545305e3fe77127084"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "4c14f78b88d792e20a8c9a48347186b3eb7d802dfcb4a06a75a2ddc714d5c8bd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "f235b62d0e240b7e9c22224516995226c2e35963"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2967423f7fc334d648209eafa2a9049318990f9feaaa07cff0c8b0f8dfdc3dde"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "c4537910e215a200114fb6e5649a1b8faa856648"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "fa43aac1c0ec794af103f9214d15d4d49cf3e2bc156755a8fd8172c2d486bd6c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6dff032aab4b0d18df608965d82d9793bdfa219"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ba6bbe788fd85d59627356ab598be7f1a5bccfd66884b52831e25f31b7a92d00"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "589f5b71636ffcb420524b9a9e730060123e723b"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "91473447f8d3edd29a234c597a41def167bca0c4e6d4dbac18cd4c1c51601839"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "441a7b910be068fd3bd81b48204252a5ee3d59df"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3034d9e2b2b4e132005369d9e3b9e8a7d961dbff4280cc9184f1866fcbd503a8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ec30999911bf1131692f7c4cb3220bbb4683c65"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "87072a76d7c0054957fc586f3c1af57b5d921a7aebcf3e22a2447178808da74c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "6e72185e9b254fcd9f39f93682597b0a9a56bf26"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "583fc0f563e664c82d7b8a7718e858bb6bb72939ccf17bf9e2de6e1659662392"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "e61fa5adf05c46fa978fa084005ebe0470a12572"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0d7a5ef0d738d4a05a341917cd48484acc15f98773b4d617694b82f39ffaf852"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "6e9c2a483bdf5dc4b0234d36e66efbe07be760b2"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2952bf681e11255d9a0b8452e9d35174540dba0b7d971d04ae03be8f8f842440"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "503bdcb10dd32ba7463fdb9afac2b9e4ddd590ca"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "b57fb07f85e93a5568b4e4c472c9e6eb06c5b42bb5c492db302b4e5a7d445cb9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "f44993f0552c28d26f60f1dcb61dc4a90bf18b03"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2dd7d7382f94036ac87fe6ed2adc38bb8d399fa29758c837a0801699559a41f2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "32217ff95c26a096fe19b67df5ac0ae93afeec4a"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "06111fa3922928913c7df80009655ba18c44ed4395b11eb3045d04c0754befff"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "b044e8a07a544943c17615ee805c2b83572119a3"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "6a90fdc45d5ca2cd74f050879e7f64c5f47808de555dde2ee9338608ca2d7ed5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c2d6a034d3569cd7734017917c129a2eb5b15add"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "84326e6fc3124772b5b4cdac41b5143c880f802ae8bdcb57dfc5df89c2ba0abe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.28+0/aws_c_common.v0.9.28.x86_64-w64-mingw32.tar.gz"
