[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "e732ec7996fd0035bcc8b16a634d6676acaf1270"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "b9a2442de72ed005949cb334255d6a442d1035087a7e69d7994d7d87b8489dbc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "b3b0eb752d5801b3497f111c4571a30a9badbd38"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "83d4fbc2138a3921ff2558691190398f1548ba3bd35845b981be46b4528efd9f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "0dfa6fc32f3aeb8922fdfc73feab09b84b134f5a"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8db39a6e7ec3f9aea63ea2a78ffcbcc87db41589fc13c33b9b09c70841f33922"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ba20b9c834ecee33ef7fa1bba26646bb660915f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2f422dbf704454b069e363489289188cc8d4b713722690f89626ba552c8f1c44"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7fc6e92373adc98ff378e2f13390ea2c1038ac9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8ad86b6a22f6297677610de55450eadc70180a2ec9f39819b33c919add675934"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba1762dbac71857bb3394161dc213b88d44f5f01"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "934ceabc66690f4e92edb37ea08d5a77b866ce6455915d10270753458164a84e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d47fd2380f3b748982aedbd7f55a0854c7a2249"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e09a1e3b60b2a1e5b4867cf3de6abf50ac4669140c04ad2f7a5739721551b110"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "0068ddead79cfbe1662f8e5ee58840de990098f7"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "71eb758195c548bc47988cd375cbc1101340b08f87884886e84897ab4aa1a543"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "427373c9acee2146024c5bee354a65ac745865f0"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "729e5cc3bdcf34ec1db3c61b7ab1897e88e08b8ae0d3d0e4f2ea06a9a4c64512"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "62795f819394086e5ad80be65b850ac072bd8e7c"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ed26157be712646de0a349f747a2cf1611ce63aa43bac55329159be2687ab052"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "9fdf6ae51b2f05cfdc0cbe14faf8f722df96fa81"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "9778c5d7fd38bb78d014ef71d9cc80509186ab6a727a4a8dac6ddc15cecadb31"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "3623fece3ced8bd88133fa60f32300862a3a4269"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d5fafbb8439eda36e9c372b29055688d035aaab7c9290ecf315f5cfdf53e8dc0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "684348e7fbe1517fb109f2dd75ad9ec2c10c00d9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0db6e73f07e75ded36577cfa2216f8331d3b11e18f1849ea244f34e8fc141e08"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a12a73a1fd7e2102f5334caa36e0c380547faca0"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "c433d39fb281bede733f819c0b2601433af3142589c73abcc1dff30f61c58ac5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "dda832b1173bb794b1a68db16decb8c9c9f5f79e"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "b2dc6cf9df3a8e653365006e857b08b7ff8075afd3a045c4bb5abb6eef4fbe67"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.15+0/aws_c_common.v0.9.15.x86_64-w64-mingw32.tar.gz"
