[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "d35d5987879e36b9566a04c89be8ca001a45a045"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "67ae5ea742599e201e95c6a65d440e9902eae2e5eab4e606e99a8750f330f937"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "181cb706089b40a0f0020c90603c9dc020baf693"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "be99896a472881f60e55751b40512e616aed487c4ff72d31cb31208e016e5d41"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "8348b4c2df114b49257726d1d3c8f86b3f2589bf"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "549fbe3a4155b223501efd6bdc0b174e6043e675e5d92bdf20f4b6ff0d99ba54"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "efc700f0c097bb9f6f038b1befa8fb278d0f1f13"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "cc210f7cfef8433b1b6ec994e1fd224bc9785284706bf5a3a97e2d6eb268a8c4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4e2b6d6148cd60c9da6c033e4bd997417e32617"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9feed39c1ec2d279ef373e097cd5cc88ec092d583b1f12e9c86495a22811203b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82e01d878656ed235a8594fa76c39915ee14a497"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "49348acdd64cbe819fc8f86456a68a03503a5b12187f9f93598fb56ac5112564"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72df155e7c0706d83537965c071fb90cf9f9cb64"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ca3f4aedd503e7ad7f8930c41e3d9477478e9948451f0375e00320575f15f6ec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05362913fddc006dba155a1cea23fb21d01f302e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c4b454874c98aa65575571105031fab32e2f146471ef22e3d0532ab278ee7db0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "480aeb1e74b2b75a3757a313e0b73137319c75bb"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f1dd582be37b756d30ff14efbcbbd0fccdb4e518c12e83718020f0eefb881be0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "83612b12159c3e48b1df93fd40eb695094d0cf5d"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "5b1511ab077e2100a2e5ce41caf2ca005608db830151db8b4a26aa8c3b5449b7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "17434182ee3db334558a196cfe7e6abf8038c83f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "20abd2d84459abd77f3f05a564426e117402f0cffaf7065dcfea106de3a82cdf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "f9df4e42acedab8d008d1c9c68573276e59c419d"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4681f31c5c6cb8dd3d5ca1a209c640ae058d8ce5d1923a2fa62c8a93ef08c97a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "9793e8a2c2fa033e9a5b7f3132824a5d61ccfed3"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "f0f43165700e73d1d8de4acb42b0783fd71d2c99717406fae6318e83e5044f34"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "6a8fac7694a8a404fde4f9b42cedbba8126655d6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8104ac5dd91c9d6ae57c298ce82e3be38c001d5ae03e56f6801e18598122fa14"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "ff663ebb8c88387cdfd9e815a4c9f066da5b5474"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0165c8555ff8796f45e9cbc7c726b46d066f177cee13695f324e214260f82bc4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c6c5e56c7c26325b7722d7d01f71f77c70b2af29"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "49d0f75cdc60cf8595b7589fe59638d321ad7743cb67d98bc9f0be986aaafb62"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a02482a8ff2189a2388d66537a3d49af21bc8a7d"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "b15713bd55e59af4fb13cfb46b92e4f6daef9a4ec5b01e4871da4ab6f8b7d03c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.11.1+0/aws_c_common.v0.11.1.x86_64-w64-mingw32.tar.gz"
