[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "8636c89cf6485aa81cb5071113d159f921095fc2"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "312eb4d81444f898879922fd4c98ad3c5a018a187cf2f11fc4bff4c3dc8a9756"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "26690fc3d9086ac772af292f0c3f142c36425f71"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "1345c361889f3f7c2e9fe05770fdd6c3016961eb4dc40295321d21f6a2f2f9ce"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "1bbec87c2f744224bae3d236e2857012c0e2ce5b"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c6bfefdd4eb7adc6c7dbad863b52b9f6b29ac8c7a65e71314224ef303da5da92"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd0c19ada317c647ac55bc06f0056f92a632c7fd"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0bbe870530cd27c0f91fe73ac4549b322104c906fdf5baebc640dfc6a7beb247"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc535bfaaaef35d7f0c47f40e0a2de38879c978c"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f0d10e1b2ab9ba7e05fe7c6fedbe89369cb293eabd65f3a05c1d75734701fb4d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a8ff8ecdb68d6d071210d283b7491721d9cb618"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3217dffd38a7c2b8e55819bc461c64b4db27079178cad22310af48b12b2bbc33"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08b8e10d6e60ada9fe7db8f0e6a4d493df43004b"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "5b4323ee61a082ba2cd644ffda0bfeacee9cac1949b5a50e8c390d5abf43437b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "5f11cd0e5ce453b2264eea6b8565ca482f2f8ad6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d06d597cac8c20ad645ed58209ed8b561354e8c806dccd42f05258c4ae74a246"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "10636213015c1a65a8eccae1783e420b94103480"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "51ee2f543c2aa539140ca29ea5327e1de7452a783d62d3362a46b52b3623dcf2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "c2b07e2904ee8f6784fdc91b1e32979cef163c10"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "b04b04b6baaa62907c68c326aad83eee3f18144cfdff14fe598d59c9d3f945d8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a32699275fbd48ea2e351fdb5bccbc77b8e6c0ca"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "d8fe24253c385e31a6fa62a1b3b49d025f69e0389c6f67cf75b2329eda5688cd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "25d64206f62eb4e18e33d2442143fd85a19ebedc"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "61659d089dc4eb8a1aae016d59070668e0e15353569ef1b25814b02d4547645c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "55d26d576cce9ed423d334972fe79a87f887b455"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0118171f3a8cb13a2c072d6759113e986cbfd0b3ebc150004f616f95f32d17ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "05bdb8b6afc6eb741b6d808c532a2ba9ac70a7be"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "e5edff6ce7a345523458e8c314873f31fbd1fbbfd16c4d6d20344479450085cd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c21e69c551c7aca44facf27e5da0d2d519112a97"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "aab611d59f549b8ea082f0a1f0c8fdd0f6313b2789d3b9dc9a197d8513e4e667"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.27+0/aws_c_common.v0.9.27.x86_64-w64-mingw32.tar.gz"
