[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "0c4f71275bb105bc5f7a1202cbd3ce18602f3eea"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "5f84a7d3ea2b7a4defeda5ecf1bab8277f3140bcd73c93f3a608fdf184537d88"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "5885c47c5df850cef33d77fd1753e706a8b0084e"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d1486f239c2830ad4c6d65af6d8bbeb78d6cec4a72c41dc82427ae4a0c4a967c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "9e0f6fc4f1deda192e4afd44f575ecbb61fb574f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "94a37155ed350983b48c31beb3b7e47e7dfe20ae462ce990e4b24afc016c434e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9aca2169541efd459497604eb89d2ed36871631"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "efbf54c3e34c0e47e04978b519c81a9972376c4eda2fd2ba1c0f685c0ee4da34"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ac5dfdd2da6b26be966d8a8ebd39b681e81ccd0"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "85b34dbf0eb15114da3e6e7621869245802605ae44e8d3eda535f080a41646fd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1f15c279220185cb7607197a8c2c021a28165db"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e7d5a8ef416e22300b4007f140ca893c4b03a01565d7f0927c132114210de40c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0631e675c19aaff231d1c2133c10c2a3c6bb7a45"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "92fd87eda293deb73b52430c3597fbd152009da20bbd4756f8c4124518761832"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "33f7433311816871af6300c890fa9ffca6a19472"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f756bbc8b003f901db60858dfc15721ff36684bd405070fc7620b4191b3481ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "c38361cbbf1e563bb4a0f04eaafafe42a774028f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c65f09a037b053ff76fda69a0bee65bc1ae8925f8db68d0b4e50ee93d17db68b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "bc51f82499409115d587833411856470e5a3c7cc"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2ad8c4fe0ecef2604cd1d7eaf67d5cbbf1f5ff925fe27894781c37657019e94e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "30b52e31aa7972788ca2b0fd2f282d0aff04aaf1"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "fcb398aaf01820b68bbed8f0b1d203e70779b54a706668ec220e53c5de30a619"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "33d6be896130536c4712ea8c996e0feed4b73b98"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6fbdf27c4940681f8ddfaf13afc13079147d6283380560f84096a28ff52f9924"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "9d33f84e25996498eb88763a6d66117097b53826"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e857f20d3bc96e01f971a9b746e048281bd844128aa0ec6d9bee645d125b8a89"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "fb4b333b7ef0cf803d915f037832fa8bb6bc2ef5"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "70c50754a5a122f2c4717187c565a0aba3a25490d153b1c590310afe88c469f9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "d042e8e69ef4d62e59a0a6391f2f4b4b876f7083"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "56238acf00c81c70fbc459eaa1c676b79852593bbc22dc4ff382a8c717af7b56"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.20+0/aws_c_common.v0.9.20.x86_64-w64-mingw32.tar.gz"
