[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "9e9a66a8b74c450892ff5b75c46d94fda932a463"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "70ea2191c2922710d646f0d58a489226dde814dbdf078440b78b7c958724fdc1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "3da06c5408fdcdc7fdc18c47db3523b30c7284d7"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "bfc7e1fb787a44b405a2007fbf02feb9ce49bf93f9883fdf735c66c4666fc159"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "182fc3f6341cbaaf06aac89ee018a5b4ca965e28"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f992f6f59dd248b6c4e8aea3854a4472b64222201c0c31be2f41cd7fb6c88fc3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd9a7bb8204e8ac764311acebe4b16603d6d4d8f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "1f1d67983a7f3134b34ee606438f4cb7150d3eb4225151e4f31bb191042e7a24"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e10242255726f4b9744f649af74a3a6f90ccd73f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9c269ff448f4c42c3a681e345155c246df5ea3c8f9e7085c626a0c1739bd1e36"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebaac4c7dd3fbe7fa7ac9529eb1f0a4b5ba98109"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2d3932a7e8098fba6e3488dc4627ff30c69b73791619fcad269d7e03e15879eb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5232135fd9765f1a440c00d75879565076f1191e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8f2f5283b775d015d9509014704cd5c961b0c8c790a367070378e4399f320892"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "6efd7c31a41d4c1052895a3c80dadd237e50fc8a"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "72ba19f44edac5e5c4ac163782699ef73cfe1ce7ca3c36717306a789bed40bf1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "73e0126c9554edf740812edb9c98ed0e1eda90e9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "aa292e4b766e8d37271579dd7b878a1292597797f375ff764a67b2f6e8ebf56f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "c9a44ef83b0a272205cb00722514d13fd8dda6a6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a7d9596e4e97bae6b82d165067d185bf884af2581b587181cbe8b9ef9e70016b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "d5c5d44ec73a40fdbb88e66324db6b433bad0a49"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "82b0ef9d55f74cf24a9e0fb9df43db2f515b8469d2fb3057a916bc3cebf517de"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "0142581b687ac8c6cb87ae7b3b8b945dd38e74a5"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "bd158fa8013cb3ca94a3d162c31b12eebadbb82baf8e2ac281a40800ff4b3a7a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "8f22006758e839a6bb67725be437cba272007927"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "58f6b65f142a5385b2ff3dc762374181b7b42120b7662e85da3b1124d51e6f26"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "64ea8028353a2d5bd7e6da96d5045396e99837e2"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "729deb68b40ed1ef09d4a6b22c60a99739835a033a777803b96cfc758a0231aa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "eb00230a8093a7ca120418926f56ebdec3462f60"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "2a1997506da7f59222111a2d4af8c14476cc608d0bce7afdf7968f4ad20ad6a7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.3+1/aws_c_common.v0.9.3.x86_64-w64-mingw32.tar.gz"
