[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "f0ceef6c683b6b7af5fd02481accb32f8bac0486"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "82db119952b02dfa8c81aa73c64ca2f870be8ae0ce5aadc64ce820cf409df1f9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "476f1c9e06e8c08cd4e8c3ca73bd87a63c608840"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "cfa2df42a8c40b7fd0c3bf74db4618da468d37533e9603dabbb5c24a68a109e8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "e4b5db6e4f498664c073f956197b2229bccac116"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6d28d00a9dcb5681f72cb323ed2fc17b39b2a25da10c7fac7e428799b348e33f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "d635b1adb54fd274297c8c7e43ce432b9a583420"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "b2170f4ce1b56f6c3ecb151b2c3e30cb66bd64d6cb4d341092e3fd2c7835a94c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3a9248edb1056ddae23720c35b5c7eca07d6da1"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "812960c8ca38341ca9cb152722e8b967d1c3e72b61a2c007238e5e3832134af9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee7a2dbd96dc57e09f9a2dd14e3e811ccb826446"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a7f823a70558eb710b32b6b62c53e594fbc10553b9e625a0462880edf7c97f4f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b85246f9f5c94eb4c3e946e79d11beeea00844d"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "dc133832c5a6f61bb88fe95bfbd9983cd4d43e32ffd7235896a5f3a07fe2c8bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9e5c42523066798ee3c2e31d787b41df0b5f930"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3a61ee068bbe34747c002d215922cb541482309b36fbb1aee540d27202d23a16"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "c193e92f8f3a8fda228ead2a264720e7ebc9cb96"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "48f286bca245bb1e424bc7b6541502294e0069f6e26c340a22d8c3b44506f9ce"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "16602a72fb57d42e78eccf6793881904c9487d3c"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "48cd7b9dc504f563d38a580a72db7d8de7032783b87c5379a0129b5d42187a3c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "46e7512bf51e4af071e1ef9e94d09b9901ec65ea"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4766af3e8d5055fea20c7a6bccb791a5c80931df7adadf62a5b0667d2610c019"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "6d74f00eadb469897111956c6376f03b9f5b5651"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f629af5160693474bbf35527c9db76852bffec268e13c995179fd3ab3005b739"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "442cfd5b8c0d9e10bd44be4da87c679f1eab0c5a"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "d99984d99f4e5707051babdc4cc914710c56cdd77640b1f5b6938702a5e40041"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "217ca301b8a64052920230cd2514de71ed4892c5"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "18add1f077c42b1443083c99edb78a8f56824e747bc1268259947db7f333e2f2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "67591a70f3906ec4997d4c726d06b57f52313448"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "dd30cfd07ad9a035e796462d9cae9a71ecd475ddc255ae09e05d1a0d2291ac97"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "9c51a59748d553305cad9d9943ecd8d5523b9c35"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "4e77902abf1725a5df4b9b41a699e5eb722c748ee425e321d10948b16296564d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "f91e217c8008d4d0a73d5d6f460e778246f9ec6b"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "4f3b938beeaf0005fc09b668f41231df0ab849ab2a9b036a842e24838388080e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.0+0/aws_c_common.v0.12.0.x86_64-w64-mingw32.tar.gz"
