[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "92396e7e0704cc399f4be10a3a90561dd3eff84d"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "cf926e9f7cd89209a29a96cf149371ab7a6569235b3f99a4876e0e08ce70fd2f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "4ad44aa16b8a612ff75b7320ffe63ebbdc5a82d4"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "cc664ea4bc7ce334ce20d506edd378ad7d4ea02696bc4a2f0f1203cc16cd079d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "b53e917d83e1fc4f8f6e296e0d7733d95b842885"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a8044ed6e0a33c8c9d0b51bb24ca0984c1a94f1473750c76ca20fce9d2c6b10e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "3dfccb4c667ef364a759f30477cb90d49af808d5"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "526290f3301b6a0b80de388141d5ab719d1816ff02eec50ff9f5466154d3d1df"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ffa7005cc5f3ae3449184bebe3245662a31eab6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "01add998493acd48b47a0a80d31811a423b37bd5f2a6c6ab66607158fe599d35"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bce8a5176c3edf8885d0eb902ae9fa6043a56b77"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "82c7ab2b40d5b1293ef671e271654447c5e5e8f7f4f03c4613b8c993d121352f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ae3f494afc3935c78cdf665a37f9ee48ce23154"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c1e50ff6147733096ae5282468d0f934d81523b09bf372e0b61edd2d7777ac15"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f256f4b0706a65c99b315e780b50d6b0a5329bfa"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "26ae152f258ca3f48e13efae3a17b4459d267fab1716df71bfff96c31556097d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "5b39ff66ff2a6f602b0917232dceef6cbe94a19a"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0e8b923b8c5bbb4f6d63521cca1208d931d2e7e1c1149d1a644c62955b7746c9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "23c0b9ab2c038e5f8e11361a435c7d986dcb9b5d"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2872a4f9f3855b889d46e1ccc1c2951aad430b2ac43dddef043fef46d1fe9272"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "2be779c2bd2b652f115a4c232d915aa0810407d6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "7b0cd8a90ff6f340ffbb56e1f6b43975635cf066bbd43ff7b689e0681409f9da"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "9cb1bdd597d0addfe9116b27a241a1ca85a88977"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6986fd597cb7a0240e5976e47973c20aac86f0313a9e445da6f2f011f5ec7597"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "79d1c63cc7b0ba76787b68ceda85743fc3034b23"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "f98e7b1f1a79948f896d3cc168fa04378656786806ab2b8cbdce9bdce1f9a414"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "8d381260057ab1a428a421aa453ff3993c6c6a6d"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "da17465e09a695ed0a9ca00176cabe508655c251a8d50c816302f6ceeff86281"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "b894b7ac5e63ba848e083d1a08a92cf20aed1de5"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0868f6ac71a5a30cd95174ba4324ec84e40739249ae971d70450de2cd3f578d5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "cf0fabb2bcdd7b009c827806a402a490b51fafa6"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "1715295f84dcd4b1d37f3bc769de59adca4e3258b8e49746544af57322812195"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a78b1c6173c424c1b41635ad3358599d30ff904e"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "6b59ea2d68e6b6b34d982a169cbbdbb797e167d63a1dbfb89b989414c4b263a6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.13.0+0/aws_c_common.v0.13.0.x86_64-w64-mingw32.tar.gz"
