[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "8068d543a9b764793847a7913672676836874881"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "f0ca538479265b79be99addc55c924f3a84ce4784352449d7c4e210dc8fa2d85"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "3ff0019ff3a7f3377af4a65fde648a86cfd3eb61"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6f28dac64ab57ee36e1df16ebd28e6deaaddf2326708607aed109ac6ced3ef13"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "dd7fd3cc691059ed6cdf3063212055891ae03b95"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c837998e163c07dff2c8cf1c2e50273a8e8ba4409189fccc1a7cbdbe6ff59d4a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "79f00cf8677e8d0445127364b88e3b8592e09285"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "acc00ab2ebcaf35450bdb5859bc37ffdb86500d415082afbea5964a5cc1fb482"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a3b900e9dd4b27c788c8620975b8405492f63be"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "1d04c08b521ec0dce0e3aa69800dbb40ae5d9ab8689c0e2fc5f9ea96cb0f0b37"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df04be20c4e799fb852a95f5de6f7bcbf0402d53"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "33808052fcb23c791845a05faf2fc0fcd0c99206666af15bcdb727aae04628c9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7798c97c220ec40c42e796f74883a68498cb13f9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "9943396c39fd7954abf28bfc07ca5107aae9bab16f0c14bdc34166afb92938cc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "4728f414241dc4b7d94a3219a80af433cd0d3a24"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0d6582b0b2d8cd7894a78e2de774cf3a641f91c1e2388f9bb893b839b0b3bbb5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "2db2536ead94ee9bdab5779cc65bbbea1d0c730f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "7546c587f3b73e5fca99df9c0567a4342efd57d044b3201481533ac8db25343f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "450b4cbc19bd5613f00e5ea059c742c490296b13"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6fa5a0e545113fad87153d74054072e66d0f30d13b9e4a46ed77ad4b33a62edf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "65509bebb758b01df6bacf33c9c334f916c48dab"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "370287c764689284cb05b59580567500aabba1996063e032e91bc62b48a9dd03"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "82533afdf6c0ac85349f6e7de13ba6d7ea0598f5"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d369b7678cd6c440e12dc14bd6f3f26a3588a5df94cbac54e9646b698a84e0e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "2209194f21109004bd51938704739e9e6179fe92"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c2af9a11d1089e3b55b5acfde7e40762f8ebfe43780543399c76b364066389e4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "bada1e6a40b755c496bfdfe2cb47c3f918b2788a"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "fa9c6525965b0213af88d0c36978f5ab0e1d6ce7893f1fda8dc9c5e6a06eeac2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "e1620e715872d8497c1cff36e5f92e0ccbc9855c"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "5280e19bb74f0924da6252b2ba2a9085bdae383660168303c048433f05cd0587"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.23+0/aws_c_common.v0.9.23.x86_64-w64-mingw32.tar.gz"
