[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "15dfc1b99561e0e2f827b3c6869840fea6931093"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "d6d5d4d9ffaddff5d03eb52992e0834627c15ad5d1aa9fa4c49bcba7db9eb86f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "2760e6be13aee5c44d47b054ad58438ec48b07e4"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4f93ff760fb2d6cf4cbd59002d0381af9dfc96ba33d2794ae1f4cec63fedc0ca"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "94bd188d74629cbc865c2c426e6ef8ad00a70cf2"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ca85ca9de0ee9f5a0bf404104d09cbee374bd8d340aaf25993502cc0acc1aaab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8004d1b7cfe578ba0c1da057ccace6d2d8450399"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e0b11125bef2bf33f5db9ca7d59b642d058cad26fd0fd5e7843e460545aaa88a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9e81ab1f7aa0be5e3356b073c4861ef0bad0df1"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6d02ef0100546b3e81d6cdce8b463003c15ea672804ce0e46b067275679d74db"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "985a8984cee705f4c15ef8138fcfc9d6f6996d41"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4d21c48b6ac292cbc501bd4efba5327a25cba76948f78c0aa92811f63fe24c17"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41d75e85601596430b3d5a3c7ece8b5d1a9b35bc"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "839d277a45fe80969298812e695f16e4171e3842ccfc53d15648eb95d9450a7c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "e6e6eabe61b4461455e9a3baffd9cf7e6912102f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d0e054904c8cf9bdaf5161e3536124e198da28858ecc623e5e521b3326ad947b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "d008cb098e5d4fba7cc7240c46fbf0cf116c41e9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "cfc8c09f451c72dcaeace4d801a3e59c36badde072c437162293af0a5378a8f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "f70294858d709fe43bc0953a2b5d2ac5c11ddc5f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a4de8c1058eeab421a0c182c2792dffcf4d4c129b0b6fb656d94a0aa3e3999d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "4c75480b7ec50da9d097b3c2f1256a09ed23d17f"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "bd054ccb8ad7ea86eab624c22569fa2f7a078b250d7c1e875c429063461f12e9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "4734c867bc0a7601eb746ce1c4b47a25af7718f6"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "20e6de0a5c98c4e34b3d3feed22fd583c61a98379fe24b3e53575e2e8a92d901"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "21878e02ad54a3766d7a2bcd678159a2866866f9"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e06ce88d6db9e6ffead54a09ad1fe2fd52329a4dfbf606d0383df3a834c0db1a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "cee9029837eb868284ceb5850e2088a03da84464"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "65abb0ccddc7bdb064d37c4627c8b2b6a916b7f73656c7a63fd8f67c2272700a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c5b3abc4254c34499424c76bacb5d671bd02de4f"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "0d680eae4b72ef9a057dd194e05a4ca35bad8dba13ddeb4b81ec1e91974f0c1e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.24+0/aws_c_common.v0.9.24.x86_64-w64-mingw32.tar.gz"
