[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "35317546b8c60080867a3482af30238f7bc58d4c"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "253c0f7f99debdb6eda9c81c4a22325450f98d3512bd8233857b711c3a6a8808"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "5ddc97fd2ec3b70e58789c33b58fa2de94134f19"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "81bf15845df0ae4e76f0e922cd68cd8a677bc9948e7f4cac28a4f57cacbb6ee2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "37c5d979257483c781286cd08f4e5e083873d51e"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3a9b8920ecbea7b1c092e79ba5bda47dc0e1f2fbf939a54b7d93597374906de1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2dba6028c654280556e86c4f6e3a9f431781505"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6417efe084ab1e5a1868eb5bee1b57271528d2118954c0cb0e6bc98fab999df6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9dbff83e9d6810c320d306a5ae8c04e2821be12"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "ce2cb70d70af0c4e8e22394c4767d94bded56769c63995c811bd3c9d8b31420d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20714ce8db9b718e85f2b7b16c59bd635ba10df0"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0b5cc68f360d53d9f9efd9ac8f5b9e0382211d9992701ac9a2feb84f60748e74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6fd474fb96d60a00e7aaab83050b784219142ecf"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "b5498f2b65bf26058d98ba126d9e0b7cc0e5d5c7b267268d6a0ff6d5d0a80f03"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "8f123534799a55581907f463b49ca997ede02b7c"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0ea139d2fad0f4ec0ecd0b93dbe411d9f7dc5caaf312b5be3071a5c6714b97d8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "3dde1a2a2139a73e2af3d5d96fcf6a398afd4293"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "3466cdfcbfc2a561ce75071db35e494d8815913d5a961e47351e11a5755e891f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "9c0ba8f507d5a4bcf1961aa71d143121fb6121d4"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c851561c5575749b0aa260665b1d598b65e6f9891228f3926af05b21ad5eb23d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "be4e4c726c299b610126739a37370200a7a9b3c2"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "dbaa333cd310d14e7697cfde3ff9acf977c5ff84739c8dc005efe00dab4afb5c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "cf115c9a45fbde9d77aa08da2fe32c02a82037fa"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "04f56550653aaa68c7c553e93cf81889fdcb23c7dbb242fe37e01e9126a50a31"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "c67c5911a9546d0c76ee032a4312aa3dbf42654a"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e0f368e298e374c9e45e82c0a381d6fc3ed2bfd27d5a32e87d8a9f285985fae2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a43a10e157af7961e9cbb381c688d4f34a825274"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "69f25d4da288ef2d850fe1ccd7577c7354fa01f3fa4cfdbd6b0e4d9ca0c815b0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "3f6d073c74038f83c5fc8c7229be28af1fdf9c7a"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "3f0ee4691526fd888b48e56d7b8b7e880f15d189cc27b7bcbbb8e3953c47fe8c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.17+0/aws_c_common.v0.9.17.x86_64-w64-mingw32.tar.gz"
