[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "e58ab35c3247064ca9323d98663abe87c0a409c9"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "2fd5ec61e9a6db38cc186179247bddc394bc51dd9c00276f5c0b6d4c0692e972"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "80c2a315a240a34ea9bfb49a1aaa2b3435776a13"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "2b47419474d38d75925c3d2d7dbf697b529c38679a5170063f29c4cbacd40791"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "81261a9de92b18b5f7aa24c14928f7769cfd4134"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "96715d979b11982617b9644a4f85fbea2b6a86f17d619f53ce58bf8f356bb128"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "43961fac291334d30a2da916059df76994934f65"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "8bbac8611e7e43ecbc0b13f1df467dcd511219130e20822604374c9a8b6edaa0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b76c8232521091aacb4881f03d0db1f1a332085"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "643ce1267a85e3908430344d4651da41bc91fe80dbe5cd1f3e4a6df017232c39"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f6af4604e74228b8e053f4a247f34894df6ca352"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "650c757a7d4f26741d4996a779b81d7d2de1ddd4f40655c3466d40590d0e318c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c2e79a79b496c6d4569e62c7b1abd7a62a9c4f8"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "c6a026afe62a675e8662cdbeaea7aca2ed3c1fbb21ba558dd0f147c057eef84e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9af9cfa52e8fd7e51ecff0f1b5f40059d19abc1"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "8a24e35641c4c3998508e325b22cda8b65e86f49cfea1d268c36fdbee255ec04"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "47dac085509d054ee66bede765b4ff98df96716b"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "04f48d67fbc9de8f22aa1b2c181c4d10e080b21b9b567a570167779c792d84f2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "0188eb389d57db5ff3a7a496521b6a9b9f31ace6"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "070a477934aff987266afc856dcc46749fd8107942869e961cd76ed4e823f9e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "dc760a2d42545002bda4cda05ae9bac58254ba5f"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "bad2a09a017ab42cf6a6c035e7ed1e8d7572727c63665529ae86a8f5a7da92d5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "0582d8934516cb8e7d09b6aa5c396ae9276b31f4"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f6400d55e3661171c5e4d72793af4cad0f7c48bfbe8d63e615507e5262f66a1a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "4db8b2ca16215fc3eb703f43f39b4047d3741221"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "165c57390b7773a1a0174b7af2c9975144b01a41d6b33e702db3de9f65b9270a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "d3c04159ad974d3059b28cf352c4225572527bf2"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "d088f5aa7a9e6105f875a776bbee600e314a2b69ddb63c6f9383b4c26446807a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "3c9dfe0a43e9cd29b32fdaeb0f973b062b7708a3"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "638208aa69ef433dc560f54bf5185a363976133e9cbe62e36dbdb39ad94797a5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "ba8bf3cb60bc45640326ae4a0429c73cafe80181"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "d71b4aeba72f9359efe89e741f4b2b684c2b6b18e8d38ddf9b9451fa5a923243"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "f91e217c8008d4d0a73d5d6f460e778246f9ec6b"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "4f3b938beeaf0005fc09b668f41231df0ab849ab2a9b036a842e24838388080e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.1+0/aws_c_common.v0.12.1.x86_64-w64-mingw32.tar.gz"
