[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "e1ac8c67c7da68e38e7653175e6d7a30372ec8ae"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "d3ffd000fc76486fa6d900174fe55cf2b97fd06d22fed83741c4145b78fd474b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "4c5b8ea8d1bac1f484b90d0c7a68f090e646911d"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f7006153bfed4428dd120dbc1ec6b7487d3c1b8783fea647d68dabcfda3a9b40"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "7cc5e87b9749f83fdceecd4d3309ebca262514a6"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "e4476e46053adb57fd4ed9e2385e16fd3543a6e623094f469bdd0452decf4190"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f959c2f64bc605673853434e31279bbd138363d"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "1d0197dc6ecc16506f89bb9edd7d6182e6a3e90afdb31d682a54be130887339d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "148c2da9fc9806b48f99a83a3b2285f2f80fa01f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6c39e77b5d59b0296869689136a7a6bd4850de24e7e32560a345abe00f7c7137"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f56a46259a680a0f9f3147a5f167469f59acf26"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "aa17779781cb628ce77d3ee68a43590a4323c17ed325730e00fe270d8ee81925"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84065636e8c806e63f5b1b9fb3f1eb74e560808f"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "afcdfc37ae07e03af430b16290390f89f9f60bf8bbb3df2a310d14ca47f437d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "ee481174008fee440d48d6d92f6d925036f1d630"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0fb0764a3e189862cb206c56c7701f1a1027f6e7a6785291a7a1abf1913bb267"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "c848d2779e770927061b2f7a9cd16a2ab4bbbb49"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "4701bc3ce5f1ba6526e9cb67ee842f1bbb16718147923ae1355d2d8edef97ef0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "88a072799b9109e7440e3a42bad01423fb889761"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "403072abd1acf8cdd84a7b5cf116fd3c0b2db1231b6db4630d0b0f41d5cd7b8c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "097b7d0dac6e5b76994249d1514a2301fd19e5d8"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "3099025094172251dd78da6491cdb2e530f02255d9ba376277bf8c7cbb9b81a0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "a498e77f1aba48b03e56626bbe2616246d73a475"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f76a90a108cb7f9cd1cd350cbb268db12eeeb12b5bfde28d7cce619f64443927"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "7699f6041c0ae4efd20f30c2df6c6fbadf241092"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "f9d4f74f5dd01a8dfeacf153b414ceeddf58e65a3a046ba5a6047dc3b9ae5be3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "6e2d5836264ccdb333508acad5a5f0a585507768"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "1f5b07fc54e40868d67ea244ede3ce2a48703b65d11ba9121261df4618ecf8cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "725937183850ea7882afd34dd91cdb56cfb3a245"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "0a7f1ff49611d3ecccd3f985c29f91b56f9bda7c12be7b7c2b150c1ebbf26801"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.9.22+0/aws_c_common.v0.9.22.x86_64-w64-mingw32.tar.gz"
