[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "066e61d1aa5ba887f608a3697a09ae9d1b3e08b2"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "2aa08785167f045b28ce72d902ae26e3cc39a9be1a2416e7223670e9600ce32d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.aarch64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "38395a253c26ecafa48629dd5ecacb71b1fe43ec"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "216c30d900e77307f7cf4600855dac539468615921208fa0f57213851073168a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.aarch64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "add0be079c4e69879efc9d1fe464deb55b1da9df"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "0306c4fd4a46ea476fa836f17c92576bbcabb1abbd7939bf701d691220d1c99e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.aarch64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "aarch64"
git-tree-sha1 = "1770547d513b15c1f4141756e4e0ee9cd83572ba"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "333f38e06be61a537d2525d89b0bcbb0c868f47ed596ace7e538594f0a8193cf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5f6d2f1b373dfbe8b05998b11bb1bc56f685167"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "679c44fe37cb12c262b192b583169c29fb84d8eee4acff3c506e761049df9508"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3dc23ca4d4dc941e017c5c662d1361f1315d52ce"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "b3abb67bb6860169827abd65f01538864c3a10405d9a39317cb66e42c79d246a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc28580483e84656cc3c8a64dd8e7d13b9263a15"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "5b679cf177380f8c7b7542d53c9c23abcadfe92d3c722789d9a1e2917d0f463d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_common]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76450355fe8683d5a00b7ff05df6cc8fcf2805a6"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "01a1b78ed87a4d3eb6cb16433259bbfc192294bedcd3e4cb5e060e61528e30b0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "418bca0a928226ba18856b04a407cb9f14d926a1"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "a7612cd3cb7a4577086ba1c9ef3bae675b7d0f5df575ff51c2c148502ef33f2a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.i686-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "i686"
git-tree-sha1 = "e36ed32cc0043fa5cc37b4542dddc718429130d5"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "5ce13d36fc11d8cfdd1c23a825d7b9e22272f94a4afb0d6e6f2cc86ee2f04413"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.i686-linux-musl.tar.gz"
[[aws_c_common]]
arch = "powerpc64le"
git-tree-sha1 = "556f49ed63326a97e72131fd42db2ac11693cd67"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "b48643e0190f4a28ca91a1c63b5c342ac388609696ae5fe52627c6243a4bd036"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "riscv64"
git-tree-sha1 = "65904cd98ad6ce4ca25ed133d6095877cd2fd9dd"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "82ed7b101a15207768f7ce039ac7645dbf5adb4d5f9719df375ce0838d53b2a4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.riscv64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "ec92e041cea745d3a19668267439788457587b38"
os = "macos"

    [[aws_c_common.download]]
    sha256 = "3747ba47c85bf72929db358fffb340d79ae3ed086ebd50abd329cb74c0d50c54"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.x86_64-apple-darwin.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "1cf9acf0ab79da28402a861403d490775dbbe936"
libc = "glibc"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "6210b06872159ba966c0bc9181f4116dc818eb381cbcd068b2f32782bcba8cec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.x86_64-linux-gnu.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "17b498a004940da9270bdba893c3c6a9cf9c3c28"
libc = "musl"
os = "linux"

    [[aws_c_common.download]]
    sha256 = "73f14de906bda9c2871359871cc55793fd24b077b2072bb85449fa560303ba63"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.x86_64-linux-musl.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "cc33d56f1e16e279516c73623db3b661c5b72efe"
os = "freebsd"

    [[aws_c_common.download]]
    sha256 = "3901562b396873dd1018b2f2760af3dbf201c5c9b7512247c42550eea752c883"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_common]]
arch = "x86_64"
git-tree-sha1 = "40e060528f20f56fc255c64ec468bceb7581529c"
os = "windows"

    [[aws_c_common.download]]
    sha256 = "7ddfcd2896bb08f9234327c97a9e39f03f764c808afe4d554da8e66588ee36dc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_common_jll.jl/releases/download/aws_c_common-v0.12.3+0/aws_c_common.v0.12.3.x86_64-w64-mingw32.tar.gz"
