# Autogenerated wrapper script for aws_c_common_jll for aarch64-apple-darwin
export libaws_c_common

JLLWrappers.@generate_wrapper_header("aws_c_common")
JLLWrappers.@declare_library_product(libaws_c_common, "@rpath/libaws-c-common.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaws_c_common,
        "lib/libaws-c-common.1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
