# Autogenerated wrapper script for aws_c_common_jll for x86_64-w64-mingw32
export libaws_c_common

JLLWrappers.@generate_wrapper_header("aws_c_common")
JLLWrappers.@declare_library_product(libaws_c_common, "libaws-c-common.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaws_c_common,
        "bin\\libaws-c-common.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
